In [24]:
import pandas as pd 
df1 = pd.DataFrame({
    'id':[1,2,3,4,5],
    # 'Name':["Ram","Shyam","Hari","Suman","Rohan"]
})
df2= pd.DataFrame({
    'id':[1,2,3,4,5],
    'Marks':[23,45,56,32,56],
    'Subject':["math","sceince","physicds","chemsistry","applied mathematics"]
})

In [25]:
df_merged = pd.merge(df1,df2,on='id')
df_merged

   id  Marks              Subject
0   1     23                 math
1   2     45              sceince
2   3     56             physicds
3   4     32           chemsistry
4   5     56  applied mathematics

In [31]:
new_df = pd.DataFrame({
    'Name':['Ram',"Shyam",'Hari'],
    'Math':[23,435,56],
    'Science':[34,45,56],
    "Physics":[34,45,56]
})
new_df

    Name  Math  Science  Physics
0    Ram    23       34       34
1  Shyam   435       45       45
2   Hari    56       56       56

In [33]:
long_form = pd.melt(
    new_df,
    id_vars=['Name'],
    var_name='Subject',
    value_name='Scores'
)
long_form

    Name  Subject  Scores
0    Ram     Math      23
1  Shyam     Math     435
2   Hari     Math      56
3    Ram  Science      34
4  Shyam  Science      45
5   Hari  Science      56
6    Ram  Physics      34
7  Shyam  Physics      45
8   Hari  Physics      56

In [42]:
wide_format = long_form.pivot_table(
    index='Name',
    columns='Subject',
    values='Scores',
)
wide_format

Subject   Math  Physics  Science
Name
Hari      56.0     56.0     56.0
Ram       23.0     34.0     34.0
Shyam    435.0     45.0     45.0

In [44]:
df = pd.DataFrame({
    'Department':['IT','IT','HR','HR'],
    'Employee':['A','B','C','D'],
    'Salary':[6000,5000,3000,5000]
})
df.head()

  Department Employee  Salary
0         IT        A    6000
1         IT        B    5000
2         HR        C    3000
3         HR        D    5000

In [52]:
table = df.pivot_table(
   index='Department',
   values='Salary',
   aggfunc='mean'
)
table

            Salary
Department
HR          4000.0
IT          5500.0

In [59]:
df['dept_mean'] = df.groupby('Department')['Salary'].transform('mean')

In [60]:
df

  Department Employee  Salary  dept_mean
0         IT        A    6000     5500.0
1         IT        B    5000     5500.0
2         HR        C    3000     4000.0
3         HR        D    5000     4000.0

## Data cleaning and Transformation

In [64]:
import numpy as np

In [81]:

df = pd.DataFrame({
    'Name':['Alice','Bob','Charlie','David','Emma'],
    'Age':[34,46,np.nan,45,np.nan],
    'Score':[45,56,np.nan,43,67]
})
df

      Name   Age  Score
0    Alice  34.0   45.0
1      Bob  46.0   56.0
2  Charlie   NaN    NaN
3    David  45.0   43.0
4     Emma   NaN   67.0

In [82]:
df_dropped = df.dropna()

In [83]:
df_dropped

    Name   Age  Score
0  Alice  34.0   45.0
1    Bob  46.0   56.0
3  David  45.0   43.0

In [115]:
df

    id   Name Department  DEPT_Code   HR   IT   PR
0  1.0    Ram         IT        1.0  NaN  NaN  NaN
1  2.0  Shyam         HR        0.0  NaN  NaN  NaN
2  3.0   Hari         PR        2.0  NaN  NaN  NaN
3  NaN    NaN        NaN        NaN  0.0  1.0  0.0
4  NaN    NaN        NaN        NaN  1.0  0.0  0.0
5  NaN    NaN        NaN        NaN  0.0  0.0  1.0

In [118]:
df.dropna()

Empty DataFrame
Columns: [id, Name, Department, DEPT_Code, HR, IT, PR]
Index: []

In [119]:
df

    id   Name Department  DEPT_Code   HR   IT   PR
0  1.0    Ram         IT        1.0  NaN  NaN  NaN
1  2.0  Shyam         HR        0.0  NaN  NaN  NaN
2  3.0   Hari         PR        2.0  NaN  NaN  NaN
3  NaN    NaN        NaN        NaN  0.0  1.0  0.0
4  NaN    NaN        NaN        NaN  1.0  0.0  0.0
5  NaN    NaN        NaN        NaN  0.0  0.0  1.0

In [84]:
df

      Name   Age  Score
0    Alice  34.0   45.0
1      Bob  46.0   56.0
2  Charlie   NaN    NaN
3    David  45.0   43.0
4     Emma   NaN   67.0

In [85]:
df['Age']= df['Age'].fillna(df['Age'].mean())
df['Score']= df['Score'].fillna(df['Score'].median())

In [86]:
df

      Name        Age  Score
0    Alice  34.000000   45.0
1      Bob  46.000000   56.0
2  Charlie  41.666667   50.5
3    David  45.000000   43.0
4     Emma  41.666667   67.0

In [93]:
df_categorical = pd.DataFrame({
    'id':[1,2,3],
    'Name':['Ram',"Shyam","Hari"],
    'Department':["IT","HR","PR"]
})

df_categorical

   id   Name Department
0   1    Ram         IT
1   2  Shyam         HR
2   3   Hari         PR

In [94]:
df_categorical.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          3 non-null      int64
 1   Name        3 non-null      object
 2   Department  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes

In [98]:
df_categorical["DEPT_Code"]=df_categorical['Department'].astype('category').cat.codes

In [99]:
df_categorical

   id   Name Department  DEPT_Code
0   1    Ram         IT          1
1   2  Shyam         HR          0
2   3   Hari         PR          2

In [113]:
encoded = pd.get_dummies(df_categorical['Department']).astype('int')
encoded

   HR  IT  PR
0   0   1   0
1   1   0   0
2   0   0   1

In [114]:
df=pd.concat([df_categorical,encoded],index=False)

TypeError: concat() got an unexpected keyword argument 'index'

In [111]:
df

    id   Name Department  DEPT_Code   HR   IT   PR
0  1.0    Ram         IT        1.0  NaN  NaN  NaN
1  2.0  Shyam         HR        0.0  NaN  NaN  NaN
2  3.0   Hari         PR        2.0  NaN  NaN  NaN
3  NaN    NaN        NaN        NaN  0.0  1.0  0.0
4  NaN    NaN        NaN        NaN  1.0  0.0  0.0
5  NaN    NaN        NaN        NaN  0.0  0.0  1.0